framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        #prefix_seed: your_vendor_name/app_name

        # The "app" cache stores to the filesystem by default.

        pools:
            cache.google_books:
                adapter: cache.adapter.filesystem
                default_lifetime: 86400

            cache.library:
                adapter: cache.adapter.filesystem
                tags: true
                default_lifetime: 3600

            cache.book_detail:
                adapter: cache.adapter.filesystem
                tags: true
                default_lifetime: 3600
