<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260512123705 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE book (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, google_volume_id VARCHAR(64) DEFAULT NULL, title VARCHAR(500) NOT NULL, subtitle VARCHAR(500) DEFAULT NULL, authors JSON NOT NULL, publisher VARCHAR(255) DEFAULT NULL, published_date VARCHAR(30) DEFAULT NULL, page_count INT DEFAULT NULL, language VARCHAR(16) DEFAULT NULL, description TEXT DEFAULT NULL, categories JSON NOT NULL, isbn10 VARCHAR(13) DEFAULT NULL, isbn13 VARCHAR(17) DEFAULT NULL, thumbnail_url VARCHAR(1000) DEFAULT NULL, cover_theme SMALLINT NOT NULL, reading_status VARCHAR(255) NOT NULL, current_page INT DEFAULT NULL, purchase_status VARCHAR(255) NOT NULL, purchased_at DATE DEFAULT NULL, purchase_format VARCHAR(60) DEFAULT NULL, rating INT DEFAULT NULL, personal_notes TEXT DEFAULT NULL, added_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, owner_id INT NOT NULL, shelf_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CBE5A3317E3C61F9 ON book (owner_id)');
        $this->addSql('CREATE INDEX IDX_CBE5A3317C12FBC0 ON book (shelf_id)');
        $this->addSql('CREATE TABLE quote (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, text TEXT NOT NULL, page INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, book_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6B71CBF416A2B381 ON quote (book_id)');
        $this->addSql('CREATE TABLE shelf (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(80) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A5475BE37E3C61F9 ON shelf (owner_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, display_name VARCHAR(80) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE book ADD CONSTRAINT FK_CBE5A3317E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE book ADD CONSTRAINT FK_CBE5A3317C12FBC0 FOREIGN KEY (shelf_id) REFERENCES shelf (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE quote ADD CONSTRAINT FK_6B71CBF416A2B381 FOREIGN KEY (book_id) REFERENCES book (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE shelf ADD CONSTRAINT FK_A5475BE37E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE book DROP CONSTRAINT FK_CBE5A3317E3C61F9');
        $this->addSql('ALTER TABLE book DROP CONSTRAINT FK_CBE5A3317C12FBC0');
        $this->addSql('ALTER TABLE quote DROP CONSTRAINT FK_6B71CBF416A2B381');
        $this->addSql('ALTER TABLE shelf DROP CONSTRAINT FK_A5475BE37E3C61F9');
        $this->addSql('DROP TABLE book');
        $this->addSql('DROP TABLE quote');
        $this->addSql('DROP TABLE shelf');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
